### PR TITLE
Add support for all platforms + SwiftPM

### PR DESCRIPTION
**Pull request by johnhammerlund**
### Problem Analysis (Technical)
This may seem a bit out-of-the-blue, but I'm interested in unifying some Okta workflows currently running on disparate tools. This library could actually provide a lot of value for Mac users; to that extent, the same argument could be applied to any of the platforms.

I didn't find any list of work-in-progress or a roadmap of sorts, so I decided to be proactive.

### Solution (Technical)
This involves a number of project changes:
- Moves all source files / test source files into a [SwiftPM-valid filestructure](https://swift.org/package-manager/#creating-a-library-package)
- Adds additional framework targets / test targets for macOS, tvOS, and watchOS
- Adds a `Package.swift`
- Updates `OktaAuthSdk.podspec` to respect the new filestructure & declare deployment targets for the additional platforms
- Updates `.travis.yml` to test all 4 platforms + SwiftPM, which are executed on separate jobs

Additionally, I've fixed a few things I found along the way:
- Removes all framework source files from test targets (some were being added to both the main target and the test target)
- Removes an unused/broken test (`AuthenticationClientTests`)

### Affected Components
Purely additive / doesn't involve interface changes

### CODE REVIEW

**Comment by johnhammerlund** [comment]
Tests are failing due to Travis fork restrictions on secure env variables (which are needed for some of the tests)

**Comment by IldarAbdullin-okta** [comment]
@johnhammerlund , thanks a lot for the contribution!
Have you signed CLA? If not please do so - https://github.com/okta/okta-auth-swift/blob/master/CONTRIBUTING.md

**Comment by johnhammerlund** [comment]
@IldarAbdullin-okta Ah, my bad, I have not. I'll do that when I get a chance later today.

**Comment by johnhammerlund** [comment]
@IldarAbdullin-okta CLA has been signed & emailed.

**Comment by IldarAbdullin-okta** [comment]
@johnhammerlund , CLA has been received, thanks! Review in progress...

**Pull request merged**
