### PR TITLE
Feature/spm support

### PR DESCRIPTION
**Pull request by mikenachbaur-okta**
### Problem Analysis (Technical)

Introduces support for Swift Package Manager, and resolves issues related to differences in test environments when run in SPM.

### Solution (Technical)

Introduces a new `Package.swift` file, as well as changes to how test resources are accessed.

### Steps to reproduce:

Actual result:

Expected result:

### CODE REVIEW

**Comment by mikenachbaur-okta** [comment]
**Note:** This is a duplicate PR from https://github.com/FinalCAD/okta-auth-swift/pull/1, but since I haven't heard a response from @Antoine4011, I'm creating this one to expedite the process for integrating this into the main repo.

**Review by IldarAbdullin-okta — APPROVED** [review]
LGTM! 👍

**Comment by mcritz** [comment]
I’m stoked about this PR! Thanks!

**Comment by Antoine4011** [comment]
Yeah sorry about that @mikenachbaur-okta, I've been busy 🙈  Great to see this coming though 💪 

I've just seen https://github.com/okta/okta-oidc-ios/pull/254 this also, so I'm super excited. Can't wait to test it! :)

**Comment by mikenachbaur-okta** [comment]
@Antoine4011 I'm currently working on addressing some test errors that's blocking the Github status checks, but your work was a very handy starting point. Thank you for starting this!

**Pull request merged**
