### PR TITLE
Add support for SPM

### PR DESCRIPTION
**Pull request by Antoine4011**
Add `Package.swift` to allows this sdk to be added through Swift Package Manager

### CODE REVIEW

**Comment by mcritz** [comment]
This project should definitely have SPM support

**Comment by mcritz** [comment]
@Antoine4011 It’d be beneficial to update the README with the SPM installation instructions.

**Comment by mikenachbaur-okta** [comment]
@Antoine4011 Building upon your original PR, I took the liberty of addressing the test failures when building using Swift Package Manager in https://github.com/FinalCAD/okta-auth-swift/pull/1.  If this looks good, feel free to merge it into your repo which should unblock #135.

Thank you!

**Comment by mikenachbaur-okta** [comment]
Swift Package Manager support has been added to v2.4.1, please try it out in the main repo. Thanks!

**Pull request closed without merging**
